import { test, expect } from '@playwright/test';

test.describe('SEO Verification', () => {
  test('Landing page has complete meta tags', async ({ page }) => {
    await page.goto('/');

    // title
    const title = await page.title();
    expect(title).toBeTruthy();
    expect(title.length).toBeGreaterThan(10);
    expect(title.length).toBeLessThan(70);

    // description
    const desc = await page.getAttribute('meta[name="description"]', 'content');
    expect(desc).toBeTruthy();
    expect(desc!.length).toBeGreaterThan(50);

    // OG tags
    const ogTitle = await page.getAttribute('meta[property="og:title"]', 'content');
    expect(ogTitle).toBeTruthy();

    const ogDesc = await page.getAttribute('meta[property="og:description"]', 'content');
    expect(ogDesc).toBeTruthy();
  });

  test('Favicon exists', async ({ page }) => {
    await page.goto('/');
    const favicon = await page.getAttribute('link[rel="icon"]', 'href');
    expect(favicon).toBeTruthy();
  });

  test('robots.txt accessible', async ({ page }) => {
    const resp = await page.goto('/robots.txt');
    // robots.txt may return 200 or 404 (auto-generated by Next.js or not)
    expect(resp?.status()).toBeLessThan(500);
  });

  test('sitemap.xml accessible', async ({ page }) => {
    const resp = await page.goto('/sitemap.xml');
    // sitemap is optional, but should not 500
    if (resp?.status() === 200) {
      const text = await page.textContent('body');
      expect(text).toContain('url');
    }
  });
});
